---
deployment:
  tasks:
    - source ~/.deploy_vars
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R pifpaf/* $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php composer.phar install --no-dev --optimize-autoloader
    - npm install
    - npm run build
    - /bin/cp .env.example .env
    - # NOTE: La configuration de la BDD dans .env doit être faite manuellement la 1ère fois.
    - /usr/local/bin/php artisan key:generate
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan storage:link
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
