---
deployment:
  tasks:
    # --- Définition des chemins (moins sécurisé) ---
    - export DEST_DIR="$HOME/deploy/pifpaf"
    - export SOURCE_DIR="$PWD" # Le dossier actuel où cPanel a cloné le dépôt

    # --- Étape de sécurité ---
    - |
      # VERROU DE SÉCURITÉ : Ne jamais déployer vers un dossier système
      if [ "$DEST_DIR" = "/" ] || [ "$DEST_DIR" = "$HOME" ]; then
        echo "ERREUR CRITIQUE : Le déploiement vers un dossier système est interdit."
        exit 1
      fi
      # Créer le dossier de destination s'il n'existe pas
      mkdir -p $DEST_DIR

    # --- Étape de déploiement ---
    - echo "Déploiement de $SOURCE_DIR vers $DEST_DIR..."
    - /usr/bin/rsync -a --delete --exclude=".git/" "$SOURCE_DIR/" "$DEST_DIR/"
    - cd $DEST_DIR/pifpaf

    # --- Étape de build Laravel ---
    - /usr/local/bin/php composer.phar install --no-dev --optimize-autoloader
    - npm install
    - npm run build
    - if [ ! -f .env ]; then cp .env.example .env; fi
    - /usr/local/bin/php artisan key:generate
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan storage:link
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - echo "Déploiement terminé."
