---
deployment:
  tasks:
    # --- Rend le script de déploiement exécutable ---
    - /bin/chmod +x deploy.sh
    # --- Exécute le script de déploiement qui contient toute la logique ---
    - /bin/bash deploy.sh
