---
deployment:
  tasks:
    # --- Définition des chemins ---
    - export DEST_DIR="$HOME/deploy/pifpaf"
    - export SOURCE_DIR="$PWD" # Le dossier où cPanel clone le code

    # --- Étape de sécurité ---
    - |
      # VERROU DE SÉCURITÉ : Ne jamais déployer vers un dossier système
      if [ "$DEST_DIR" = "/" ] || [ "$DEST_DIR" = "$HOME" ]; then
        echo "ERREUR CRITIQUE : Le déploiement vers un dossier système est interdit."
        exit 1
      fi
      # Créer le dossier de destination s'il n'existe pas
      mkdir -p $DEST_DIR

    # --- Étape de déploiement ---
    - echo "Déploiement de $SOURCE_DIR vers $DEST_DIR..."
    - /usr/bin/rsync -a --delete --exclude=".git/" "$SOURCE_DIR/" "$DEST_DIR/"
    - cd $DEST_DIR/pifpaf

    # --- Étape de build ---
    - |
      echo "Activation de l'environnement Node.js..."
      # La commande que vous avez fournie pour activer Node.js et npm
      source /home/sc1wrpg9004/nodevenv/deploy/pifpaf/pifpaf/22/bin/activate
      
      echo "Lancement de npm install..."
      npm install
      
      echo "Lancement de npm run build..."
      npm run build

    - echo "Installation des dépendances Composer..."
    - /usr/local/bin/php composer.phar install --no-dev --optimize-autoloader

    - echo "Configuration de l'application Laravel..."
    - if [ ! -f .env ]; then cp .env.example .env; fi
    - /usr/local/bin/php artisan key:generate
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan storage:link
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - echo "Déploiement terminé avec succès !"
